"use client";
import { useEffect, useMemo, useState } from "react";

type OrderStatus = "CREATED"|"QUOTED"|"PAYMENT_PENDING"|"PAID"|"ISSUING"|"ISSUED"|"FAILED"|"REFUND_REQUIRED";
type Order = { id:string; externalRef:string; status:OrderStatus; maskedPlate:string; premiumCents?:number; policyNumber?:string; correlationId:string; createdAt:string; updatedAt:string };
type OrderEvent = { id:string; orderId:string; eventType:string; payload:Record<string,unknown>; occurredAt:string };

export default function Home() {
  const [orders,setOrders]=useState<Order[]>([]); const [filter,setFilter]=useState<string>(""); const [query,setQuery]=useState(""); const [selected,setSelected]=useState<Order|null>(null); const [events,setEvents]=useState<OrderEvent[]>([]);
  useEffect(()=>{ let active=true; const load=async()=>{const r=await fetch("/api/orders",{cache:"no-store"}); if(r.ok&&active)setOrders(await r.json() as Order[])}; void load(); const id=setInterval(()=>void load(),5000); return()=>{active=false;clearInterval(id)}},[]);
  const visible=useMemo(()=>orders.filter(o=>(!filter||o.status===filter)&&(!query||o.id.toLowerCase().includes(query.toLowerCase())||o.externalRef.toLowerCase().includes(query.toLowerCase()))),[orders,filter,query]);
  const openDetail=async(order:Order)=>{setSelected(order);setEvents([]);const r=await fetch(`/api/orders/${encodeURIComponent(order.id)}/events`,{cache:"no-store"});if(r.ok)setEvents(await r.json() as OrderEvent[])};
  const runAction=async(action:"retry-issuance"|"mark-refund-required")=>{if(!selected||!confirm("¿Confirmas esta acción operativa?"))return;const r=await fetch(`/api/orders/${encodeURIComponent(selected.id)}/${action}`,{method:"POST",headers:{"X-Actor-ID":"video-demo"}});if(!r.ok){const body=await r.json() as {error?:string};alert(body.error??"La acción no pudo ejecutarse");return}setSelected(null)};
  return <main><header><div><p className="eyebrow">OPERATIONS</p><h1>Insurance Control Center</h1><p>Seguimiento de pagos, emisiones y excepciones operativas.</p></div><span className="live">● ACTUALIZACIÓN 5 S</span></header>
    <section className="filters"><input aria-label="Buscar" placeholder="Buscar orden o referencia" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Estado" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Todos los estados</option>{["CREATED","QUOTED","PAYMENT_PENDING","PAID","ISSUING","ISSUED","FAILED","REFUND_REQUIRED"].map(s=><option key={s}>{s}</option>)}</select></section>
    <section className="summary"><article><strong>{orders.length}</strong><span>Total órdenes</span></article><article><strong>{orders.filter(o=>o.status==="ISSUED").length}</strong><span>Emitidas</span></article><article className="warning"><strong>{orders.filter(o=>o.status==="REFUND_REQUIRED").length}</strong><span>Requieren reverso</span></article></section>
    <section className="table"><table><thead><tr><th>Orden</th><th>Estado</th><th>Vehículo</th><th>Prima</th><th>Actualización</th></tr></thead><tbody>{visible.map(o=><tr className="order-row" key={o.id} onClick={()=>void openDetail(o)}><td><b>{o.id}</b><small>{o.externalRef}</small></td><td><span className={`status ${o.status.toLowerCase()}`}>{o.status}</span></td><td>{o.maskedPlate}</td><td>{o.premiumCents?new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0}).format(o.premiumCents/100):"—"}</td><td>{new Date(o.updatedAt).toLocaleString("es-CO")}</td></tr>)}</tbody></table>{visible.length===0&&<p className="empty">No hay órdenes que coincidan con el filtro.</p>}</section>
    {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><section className="detail" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><p className="eyebrow">DETALLE DE ORDEN</p><h2>{selected.id}</h2><div className="detail-grid"><span><small>Estado</small><b>{selected.status}</b></span><span><small>Vehículo</small><b>{selected.maskedPlate}</b></span><span><small>Póliza</small><b>{selected.policyNumber||"Pendiente"}</b></span><span><small>Correlation ID</small><b>{selected.correlationId}</b></span></div>{selected.status==="ISSUING"&&<div className="actions"><button onClick={()=>void runAction("retry-issuance")}>Reintentar emisión</button><button className="danger" onClick={()=>void runAction("mark-refund-required")}>Marcar para reverso</button></div>}<h3>Línea de tiempo</h3><ol className="timeline">{events.map(event=><li key={event.id}><div><b>{event.eventType}</b><small>{new Date(event.occurredAt).toLocaleString("es-CO")}</small></div><code>{JSON.stringify(event.payload)}</code></li>)}</ol>{events.length===0&&<p>Cargando eventos…</p>}</section></div>}
  </main>;
}
